/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.parcial_dos;

import javax.swing.JOptionPane;

/**
 *
 * @author escobarlima
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1_necflis = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1_clientes = new javax.swing.JMenu();
        jMenuItem1_VerListado = new javax.swing.JMenuItem();
        jMenuItem2_NuevoCliente = new javax.swing.JMenuItem();
        jMenuItem3_SeleccionarCliente = new javax.swing.JMenuItem();
        jMenu2_peliculas = new javax.swing.JMenu();
        jMenuItem4_NombrePeli = new javax.swing.JMenuItem();
        jMenuItem5_TipoPeli = new javax.swing.JMenuItem();
        jMenuItem6_GeneroPeli = new javax.swing.JMenuItem();
        jMenuItem7_SinopsisPeli = new javax.swing.JMenuItem();
        jMenu5_Salir = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1_necflis.setFont(new java.awt.Font("Oriya MN", 0, 24)); // NOI18N
        jLabel1_necflis.setText("NECFLIS");

        jMenu1_clientes.setText("Clientes");

        jMenuItem1_VerListado.setText("Ver listado de clientes");
        jMenu1_clientes.add(jMenuItem1_VerListado);

        jMenuItem2_NuevoCliente.setText("Crear nuevo cliente");
        jMenuItem2_NuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_NuevoClienteActionPerformed(evt);
            }
        });
        jMenu1_clientes.add(jMenuItem2_NuevoCliente);

        jMenuItem3_SeleccionarCliente.setText("Seleccionar cliente");
        jMenuItem3_SeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_SeleccionarClienteActionPerformed(evt);
            }
        });
        jMenu1_clientes.add(jMenuItem3_SeleccionarCliente);

        jMenuBar2.add(jMenu1_clientes);

        jMenu2_peliculas.setText("Peliculas");

        jMenuItem4_NombrePeli.setText("Nombre");
        jMenu2_peliculas.add(jMenuItem4_NombrePeli);

        jMenuItem5_TipoPeli.setText("Tipo");
        jMenuItem5_TipoPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_TipoPeliActionPerformed(evt);
            }
        });
        jMenu2_peliculas.add(jMenuItem5_TipoPeli);

        jMenuItem6_GeneroPeli.setText("Género");
        jMenu2_peliculas.add(jMenuItem6_GeneroPeli);

        jMenuItem7_SinopsisPeli.setText("Sinopsis");
        jMenu2_peliculas.add(jMenuItem7_SinopsisPeli);

        jMenuBar2.add(jMenu2_peliculas);

        jMenu5_Salir.setText("Salir");
        jMenuBar2.add(jMenu5_Salir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1_necflis)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1_necflis)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3_SeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_SeleccionarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3_SeleccionarClienteActionPerformed

    private void jMenuItem5_TipoPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_TipoPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5_TipoPeliActionPerformed

    private void jMenuItem2_NuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_NuevoClienteActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenuItem2_NuevoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_necflis;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu1_clientes;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu2_peliculas;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5_Salir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1_VerListado;
    private javax.swing.JMenuItem jMenuItem2_NuevoCliente;
    private javax.swing.JMenuItem jMenuItem3_SeleccionarCliente;
    private javax.swing.JMenuItem jMenuItem4_NombrePeli;
    private javax.swing.JMenuItem jMenuItem5_TipoPeli;
    private javax.swing.JMenuItem jMenuItem6_GeneroPeli;
    private javax.swing.JMenuItem jMenuItem7_SinopsisPeli;
    // End of variables declaration//GEN-END:variables
}
